apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: blob-fuse2-premium

provisioner: blob.csi.azure.com
parameters:
  protocol: fuse2
  skuName: Premium_LRS

mountOptions:
  - -o allow_other
  - --file-cache-timeout-in-seconds=120
  - --use-attr-cache=true
  - --cancel-list-on-mount-seconds=10
  - -o attr_timeout=120
  - -o entry_timeout=120
  - -o negative_timeout=120
  - --log-level=LOG_WARNING
  - --cache-size-mb=1000

allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate